apiVersion: v1
kind: Service
metadata:
    labels:
        app: comments
    name: comments-svc
    namespace: default
    selfLink: /api/v1/namespaces/default/services/feeds-svc
spec:
    ports:
        - port: 8080
          protocol: TCP
          targetPort: 8080
    selector:
        app: comments 
    sessionAffinity: None
    type: ClusterIP
status:
    loadBalancer: {}
