apiVersion: v1
kind: Service
metadata:
    labels:
        app: users
    name: users-svc
    namespace: default
    selfLink: /api/v1/namespaces/default/services/users-svc
spec:
    ports:
        - port: 8080
          protocol: TCP
          targetPort: 8080
    selector:
        app: users
    sessionAffinity: None
    type: ClusterIP
status:
    loadBalancer: {}
